### PR TITLE
Load samples into buffers

### PR DESCRIPTION
**Pull request by chrislo**
While using barcode, I found myself wanting to load samples from the norns filesystem (in particular the contents of the internal "tape") easily. In this PR I've added two parameter menu entries to load a sample into either of the two buffers. 

I've decided to use the parameter menu for this in a similar way to how `cheat codes` works. I also considered a parameter toggle to switch recording "mode" from either input or file, and then modifying the behaviour of K3. But I couldn't find an easy way to launch a file picker from a key press. 

I haven't currently added any error checking on the loaded file (such as its presence, or length). 

Would you be interested in incorporating this PR @schollz? I'm happy to rework it if it might be useful - this is my first bit of norns scripting so I may not be using best practices!

### CODE REVIEW

**Comment by schollz** [comment]
this is great!! its been a highly requested feature and i never go around to doing it. thank you so much! i'll test it out this weekend as i don't have the norns with me for the time being. (but it looks totally fine to me! just want to make sure)

**Comment by chrislo** [comment]
That's great @schollz thanks! I've been playing with it a bit since and I've noticed that I sometimes need to tap record for the newly loaded buffers to sound correct. Perhaps we also need to set the buffer length somewhere after loading a sample? I'll take a look as well if I get chance.

**Comment by chrislo** [comment]
I've opened https://github.com/schollz/barcode/pull/14 which is the alternative approach I suggested above (changing the behaviour of K3 based on a param). I think I prefer #14 to this PR, but interested to hear your thoughts @schollz.

**Comment by schollz** [comment]
thanks. i actually would prefer this one. i think it makes sense because its much more common to load a file once, rather than many times, and it would be useful to load a file and then overdub it. also i try as often as possible to make one button do one thing (but its hard to do this all the time).

i think the issues going on can be fixed by running the code that is supposed to run at the end of a recording, namely [these lines](https://github.com/schollz/barcode/blob/master/barcode.lua#L416-L421).

namely you can figure out how long the sample is and the load it and then set the size and the recorded flag:

```lua
  state.recordingtime = <duration of clip>
  state.has_recorded=1
  -- change the buffer size (only if its bigger)
  if state.buffer_size[state.buffer]==60 or state.recordingtime>state.buffer_size[state.buffer] then
    state.buffer_size[state.buffer]=state.recordingtime
  end
```

actually now that i think about it, you should probably load only 60 seconds max since thats the limit (arbitrary) that i have for recording.

you can get the duration using [this code](https://github.com/schollz/oooooo/blob/master/oooooo.lua#L974-L975).

**Comment by chrislo** [comment]
Great thank you @schollz - I think I figured out setting the buffer duration in the other PR. I'll incorporate that into this one shortly 👍

**Comment by chrislo** [comment]
I've just implemented setting the buffer size after loading the sample. I've rewritten the history to include that change and force-pushed. Let me know what you think @schollz.

**Comment by schollz** [comment]
sounds great and works great for me! ready to merge?

**Comment by chrislo** [comment]
I think so, if you're happy 🙂

**Comment by schollz** [comment]
excellent, merged!!! thanks!

**Comment by chrislo** [comment]
Thank you for all of your support with my first norns contribution!

**Comment by schollz** [comment]
@chrislo thank YOU for your contribution!

**Pull request merged**
